### ISSUE TITLE
run through default dcgan

### ISSUE THREAD

**Issue by raynardj** [twairball/tensor2gan#5]
run through default dcgan, things need to be debugged

**Comment by raynardj** [comment]
Error messege,
 a type error in logging process, filter numbers are list
```
INFO:tensorflow:Skipping writing TFRecord, found: ./data/cifar10_train.tfrecords
--- Logging error ---
Traceback (most recent call last):
  File "/home/zhangxiaochen/anaconda3/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/home/zhangxiaochen/anaconda3/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/home/zhangxiaochen/anaconda3/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/home/zhangxiaochen/anaconda3/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "gan_trainer", line 143, in <module>
    tf.app.run()
  File "/home/zhangxiaochen/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "gan_trainer", line 78, in main
    losses, outputs, optimizers = gan.model(inputs) # returns dicts
  File "/home/zhangxiaochen/github/tensor2gan/tensor2gan/models/dcgan.py", line 144, in model
    fake_data = self.G(z)
  File "/home/zhangxiaochen/github/tensor2gan/tensor2gan/models/dcgan.py", line 27, in __call__
    tf.logging.info("[generator] filters: ", [f0, f1, f2, f3, f4])
  File "/home/zhangxiaochen/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/tf_logging.py", line 82, in info
    _logger.info(msg, *args, **kwargs)
Message: '[generator] filters: '
Arguments: ([1024, 512, 256, 128, 3],)
INFO:tensorflow:[disc] filters: [64, 128, 256, 512]
INFO:tensorflow:[discriminator] input shape: (?, 32, 32, 3)
INFO:tensorflow:[disc] filters: [64, 128, 256, 512]
INFO:tensorflow:[discriminator] input shape: (?, 32, 32, 3)
Traceback (most recent call last):
  File "gan_trainer", line 143, in <module>
    tf.app.run()
  File "/home/zhangxiaochen/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "gan_trainer", line 78, in main
    losses, outputs, optimizers = gan.model(inputs) # returns dicts
  File "/home/zhangxiaochen/github/tensor2gan/tensor2gan/models/dcgan.py", line 150, in model
    d_fake=d_fake
AttributeError: can't set attribute
```
